# Generated by Django 3.2 on 2024-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classmate',
            field=models.CharField(db_column='class', db_index=True, default='10', max_length=5, verbose_name='班级'),
            preserve_default=False,
        ),
    ]
