# Generated by Django 3.2 on 2024-12-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu', to='student.studentdetail'),
        ),
    ]
